### ISSUE TITLE
Runtime Error: Exit Code 128

### ISSUE THREAD

**Issue by SqueamishStudio** [adrirubio/Mindful#7]
Was testing your demo and got this error:

`Exit code: 128. Reason: failed to create containerd task: failed to create shim task: context canceled: unknown`

I believe it may have something to do with the API key being used but not sure. Here's a screenshot below of the problem.

![image](https://github.com/user-attachments/assets/f7823b70-1383-4c60-b1b6-e0a91e8b050f)

**Comment by adrirubio** [comment]
Yes, I already created the hugging face space, but I still need to finish the model to add it here
