### ISSUE TITLE
Potentially incorrect parameter freezing in transfer_learning_chatbot.py

### ISSUE THREAD

**Issue by AlanDoesCS** [adrirubio/Mindful#9]
# Describe the issue
I'm not 100% certain, but I'm pretty sure that in this code snippet from `transfer_learning_chatbot.py`, that the layers are being frozen/unfrozen incorrectly:

```python
# Unfreeze some layers
for param in model.model.decoder.embed_tokens.parameters():
    param.requires_grad = True
for param in model.model.decoder.embed_positions.parameters():
    param.requires_grad = True
# Unfreeze last 4 layers of the decoder
for layer in model.model.decoder.layers[-4:]:
    for param in layer.parameters():
        param.requires_grad = True
```

I may be wrong, but I would assume that all parameters would have to be frozen first before running this, in order to specifically target these parameters.

**Comment by AlanDoesCS** [comment]
@adrirubio Do you know if we should freeze all parameters first, before this snippet?

**Comment by adrirubio** [comment]
Yes, that's right it would of been a good idea to freeze all before freezing the last four!
I fixed it by adding this:

`# First freeze everything`
`for param in model.parameters():`
    `param.requires_grad = False`
    
  Thanks for letting me know!

**Comment by AlanDoesCS** [comment]
No worries Adrian :)
and thanks for resolving this issue so fast!
